#pragma config(Sensor, S1,     Color1,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true) {
		if(getColorHue(Color1) < 100) {
			setMotorSpeed(LeftMotor, 15);
			setMotorSpeed(RightMotor, 20);
		}
		else {
			setMotorSpeed(LeftMotor, 20);
			setMotorSpeed(RightMotor, 15);
		}

		displayBigTextLine(1, "Hue: %d", getColorHue(Color1));
	}

}
