#pragma config(Sensor, S1,     Color1,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define WHEELDIAMETER 7 // Wheel diameter in cm
#define ENCODER_COUNT_REVOLUTION 360 // How many encoder counts goes to one revolution

float calcDistMoved() {
	return ((PI*WHEELDIAMETER)/ENCODER_COUNT_REVOLUTION) * (getMotorEncoder(LeftMotor)+getMotorEncoder(RightMotor))/2;
}

task main()
{

	while(true) {
		displayBigTextLine(0, "%f", calcDistMoved());

		while(calcDistMoved() < 55.0) {
			setMotorSpeed(LeftMotor, 15);
			setMotorSpeed(RightMotor, 15);
		}

		setMotorSpeed(LeftMotor, 0);
		setMotorSpeed(RightMotor, 0);

		displayBigTextLine(0, "%f", calcDistMoved());

		delay(100000);
	}



}
