#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(leftMotor, 1);
	while(true) {
		displayBigTextLine(1, "Encoder: %d", getMotorEncoder(leftMotor));
	}
}
