#pragma config(Sensor, S1,     Ranger,         sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		while(getUSDistance(Ranger) > 30) {
			unsigned short dist = getUSDistance(Ranger);
			displayBigTextLine(1, "Distance %d", dist);
			setMotorSpeed(LeftMotor, 60);
			setMotorSpeed(RightMotor, 60);
		}
			setMotorSpeed(LeftMotor, 0);
			setMotorSpeed(RightMotor, 0);
	}
}
