#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DISPLAYX 178
#define DISPLAYY 128
#define DISPCENTERX DISPLAYX/2
#define DISPCENTERY DISPLAYY/2


float circleCoordsX(int a, int radius, float t);
float circleCoordsY(int b, int radius, float t);

task main()
{
	clearTimer(timer1);

	float slize = (2*PI)/360;
	while(true) {
		float gyro = getGyroDegrees(Gyro);


		if(getTimerValue(timer1) > 500) {
			eraseDisplay();
			drawLine(DISPCENTERX, DISPCENTERY, circleCoordsX(DISPCENTERX, 64, gyro*slize), circleCoordsY(DISPCENTERY, 64, gyro*slize));
			displayBigTextLine(0, "Gyro: %d", gyro);
			displayBigTextLine(3, "X: %f", circleCoordsX(DISPCENTERX, 64, gyro*slize));
			displayBigTextLine(5, "Y: %f", circleCoordsY(DISPCENTERY, 64, gyro*slize));
			clearTimer(timer1);
		}
	}

}




float circleCoordsX(int a,int radius, float t) {
	return a+radius*cos(t);
}

float circleCoordsY(int b, int radius, float t) {
	return b+radius*sin(t);
}
